CREATE SEQUENCE address_seq INCREMENT 1 START 60 MINVALUE 1;

CREATE SEQUENCE balances_seq INCREMENT 1 START 10 MINVALUE 1;

CREATE SEQUENCE callers_seq INCREMENT 1 START 15 MINVALUE 1;

CREATE SEQUENCE clients_seq INCREMENT 50 START 15 MINVALUE 1;

CREATE SEQUENCE connectionPrices_seq INCREMENT 1 START 4 MINVALUE 1;

CREATE SEQUENCE connectionRequests_seq INCREMENT 1 START 15 MINVALUE 1;

CREATE SEQUENCE installingPossibilities_seq INCREMENT 1 START 30 MINVALUE 1;

CREATE SEQUENCE ldcPrices_seq INCREMENT 1 START 3 MINVALUE 1;

CREATE SEQUENCE ldc_seq INCREMENT 1 START 15 MINVALUE 1;

CREATE SEQUENCE phoneNumbers_seq INCREMENT 1 START 15 MINVALUE 1;

CREATE SEQUENCE phoneTypes_seq INCREMENT 1 START 5 MINVALUE 1;

CREATE SEQUENCE phones_seq INCREMENT 1 START 15 MINVALUE 1;

CREATE SEQUENCE publicPhones_seq INCREMENT 1 START 15 MINVALUE 1;

CREATE SEQUENCE subscriptionFees_seq INCREMENT 1 START 15 MINVALUE 1;

CREATE SEQUENCE Exchanges_seq INCREMENT 1 START 5 MINVALUE 1;